// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN3qkRbdgCMJr-pSctv-sdg6M4GP5nxVM',
    appId: '1:362492285914:web:131e4ff3327f9d76ba66e3',
    messagingSenderId: '362492285914',
    projectId: 'safariconnect-de676',
    authDomain: 'safariconnect-de676.firebaseapp.com',
    storageBucket: 'safariconnect-de676.firebasestorage.app',
    measurementId: 'G-QDTYGQ65WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBliX_ybvW1DUpl7iNTi_50zTi8uoCwRUI',
    appId: '1:362492285914:android:47c1a996145c44adba66e3',
    messagingSenderId: '362492285914',
    projectId: 'safariconnect-de676',
    storageBucket: 'safariconnect-de676.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyQ_Kypv8NbClKdHEu0S6hb0N0wHUYIRo',
    appId: '1:362492285914:ios:1e1b0cbf50eac842ba66e3',
    messagingSenderId: '362492285914',
    projectId: 'safariconnect-de676',
    storageBucket: 'safariconnect-de676.firebasestorage.app',
    iosBundleId: 'com.example.mapproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyQ_Kypv8NbClKdHEu0S6hb0N0wHUYIRo',
    appId: '1:362492285914:ios:1e1b0cbf50eac842ba66e3',
    messagingSenderId: '362492285914',
    projectId: 'safariconnect-de676',
    storageBucket: 'safariconnect-de676.firebasestorage.app',
    iosBundleId: 'com.example.mapproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN3qkRbdgCMJr-pSctv-sdg6M4GP5nxVM',
    appId: '1:362492285914:web:eee4ecd0dd8a015fba66e3',
    messagingSenderId: '362492285914',
    projectId: 'safariconnect-de676',
    authDomain: 'safariconnect-de676.firebaseapp.com',
    storageBucket: 'safariconnect-de676.firebasestorage.app',
    measurementId: 'G-YWVH4T4J3N',
  );
}
